language: generic

git:
  depth: false

install:
- docker pull fedora:30

script:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- docker run -eBRANCH -eGH_NAME -eGH_EMAIL -eGH_TOKEN --network host -it --volume $PWD:/docs:z --workdir /docs fedora:30 /bin/bash -c './build_tools/travis.sh'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
