# Site settings
show_downloads: false
title: 'Forklift'
description: "Upstream project for migrating VMware virtual machines to OpenShift Virtualization."
permalink: pretty
repository: apinnick/mtv-test
baseurl: /mtv-test/


plugins: [jekyll-paginate, jekyll-asciidoc, jekyll-redirect-from, jekyll-feed, jekyll-sitemap, premonition, jekyll/tagging,  jekyll-seo-tag, jekyll-remote-theme]

# Site settings
future: false

title: "Forklift"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# theme: jekyll-rtd-theme
# title: Forklift
# repo_url: 'https://github.com/apinnick/mtv-test'
# baseurl: '/mtv-test'
#
# plugins:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-gist
#   - jekyll-feed
#   - jekyll-remote-theme
#   - jekyll-github-metadata
