# frozen_string_literal: true
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

source "https://rubygems.org"

gem "asciidoctor-pdf"
gem "asciidoctor"
gem "bundle"
gem 'prawn', '= 2.2.2'
gem "pdf-core", ">= 0.7.0"
gem "html-proofer"
gem "jekyll-asciidoc"
gem "jekyll-feed"
gem "jekyll-paginate"
gem "jekyll-redirect-from"
gem "jekyll-sitemap"
gem "jekyll-tagging"
gem 'jekyll-seo-tag'
gem "jekyll"
gem "premonition", ">= 4.0.0"
gem "pygments.rb"
gem "rake"
gem "jekyll-gist"
gem "jekyll-remote-theme"
gem "github-pages"
gem "jekyll-github-metadata"
gem "jekyll-rtd-theme"


# gem "rails"
